# Header
menu:
  twoseven.xyz:
    href: https://twoseven.xyz
    target: _blank
  About:
    href: /about
  twitter:
    html: '<a href="https://twitter.com/twosevenxyz" target="_blank"><i class="fa fa-twitter" style="font-size: 1.2em; color: #1da1f2;"></a>'
  facebook:
    html: '<a href="https://twitter.com/twosevenxyz" target="_blank"><i class="fa fa-facebook-f" style="font-size: 1.2em; color: #3B5998;"></a>'


rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
favicon: images/favicon
twitter: twosevenxyz
google_plus:
fb_admins:
fb_app_id:
show_powered_by: false

stylus:
  compress: false
